# Generated by Django 4.0 on 2022-01-06 20:13

from django.db import migrations, models
import gambeling_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('gambeling_backend', '0002_alter_profile_address1_alter_profile_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./AvatarMale.png', null=True, upload_to=gambeling_backend.models.Profile.user_directory_path),
        ),
    ]
